@EarlyRetirement.Api_HostAddress = https://localhost:7155

POST {{EarlyRetirement.Api_HostAddress}}/users/register
Content-Type: application/json

{
  "email": "wrong",
  "password": "123",
  "confirmPassword": "321"
}